### ISSUE TITLE
XL320 address map differs from XC430

### ISSUE THREAD

**Issue by JamesNewton** [hideakitai/Dynamixel#1]
If we take a quick look at:
<strike>http://emanual.robotis.com/docs/en/dxl/x/xc430-w240/</strike>
http://emanual.robotis.com/docs/en/dxl/x/xl320/#control-table-of-eeprom-area
it becomes obvious that they've changed it all around compared, for example, to the XC430.  Right off the bat, we find that the XC430 starts at 57.6K and the XL320 starts at 1M. Also, the control register to change that is at address 8 vs 4, and the values you put into that register are also different. These differences continue on... the goal position is now at address 116, vs 30. This library appears to assume all X series are the same, so it can't support the <strike>XC430</strike>. 

I assume the best way to fix this is to add a new map to 
https://github.com/hideakitai/Dynamixel/blob/master/Dynamixel/DynamixelControlTable.h
which includes a register layout for the XC series vs the X series?

**Comment by hideakitai** [comment]
@JamesNewton Sorry for late reply! Exactly X series is not completely same as XC series. But I don't have that and can't test it. Could you give me PR? Thanks!
