### ISSUE TITLE
How to wire the Dynamixel to the Arduino

### ISSUE THREAD

**Issue by ceinem** [hideakitai/Dynamixel#4]
Hi, could you provide some more information on how to connect the Dynamixel to the Arduino? 
Are you using the Dynamixel Shield, or directly connection the serial ports? Or using something like a Tri-State? 

I want to connect an MX-12W to an Arduino Zero, but am having issues due to the half-duplex serial port of the servo.

**Comment by hideakitai** [comment]
@ceinem Hi, thanks for reporting. You can connect the serial port as you want if the electrical spec is correct. ~But this library does not consider a half-duplex serial port inside. Please write your own code carefully not to overwrap writing and reading.~ Sorry, this library considers a half-duplex port by using RTS_PIN or TX_ENABLE/RX_ENABLE pins.

```C++
Dynamixel dxl(PIN_RTS);
// or
Dynamixel dxl(PIN_RX_ENABLE, PIN_TX_ENABLE);
```

**Comment by hideakitai** [comment]
I will close this issue but feel free to reopen if you still have a problem.

**Comment by ceinem** [comment]
Hi @hideakitai, thanks for the help! I was having some further issues getting the half-duplex communication working, but that was independent of your library. I will test again next week once I have new components. If I still have issues getting it running, I will reopen.

**Comment by tsbertalan** [comment]
What should we be doing with the
```c++
#define DYNAMIXEL_SERIAL Serial2 // change as you want
```
line? I'm using an Arduino Uno at the moment, with ground and Digital 11 pins connected to Gnd- and Data on the SMPS2Dynamixel power board, respectively.
